Add debugging to region loop

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -296,6 +296,11 @@ jobs:
           GITHUB_TOKEN: ${{ steps.app-token-2.outputs.token }}
           REGIONS: east-midlands east-of-england london north-east north-west northern-ireland scotland south-east south-west wales west-midlands yorkshire-and-the-humber
         run: |
+          # output debugging info
+          set -x
+          set -o errexit -o nounset -o pipefail
+          trap 'echo "ERROR: command failed on line $LINENO: $BASH_COMMAND (exit $?)"' ERR
+
           for REGION in ${REGIONS:-}; do
             echo "Processing region: ${REGION}"
 
