Split establishments into region folders and repos

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -173,36 +173,195 @@ jobs:
           private-key: ${{ secrets.APP_PRIVATE_KEY }}
           owner: ${{ github.repository_owner }}
 
+      # We can not create a package due to size, so this is all inline instead of separate jobs
+      #
+      # 1. Extract region repositories
+      # 2. Loop over regions
+      #   a. Prepare public directory in repository
+      #   b. Copy generated site to public directory
+      #   c. Commit and push changes
+
+      # Hardcoded regions / itl regions
+
+      # region-east-midlands
+      - name: Checkout region-east-midlands repository
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          repository: food-hygiene-uk/region-east-midlands
+          path: ./repos/region-east-midlands
+          token: ${{ steps.app-token-2.outputs.token }}
+          fetch-depth: 1
+
+      # region-east-of-england
+      - name: Checkout region-east-of-england repository
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          repository: food-hygiene-uk/region-east-of-england
+          path: ./repos/region-east-of-england
+          token: ${{ steps.app-token-2.outputs.token }}
+          fetch-depth: 1
+
+      # region-london
+      - name: Checkout region-london repository
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          repository: food-hygiene-uk/region-london
+          path: ./repos/region-london
+          token: ${{ steps.app-token-2.outputs.token }}
+          fetch-depth: 1
+
+      # region-north-east
+      - name: Checkout region-north-east repository
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          repository: food-hygiene-uk/region-north-east
+          path: ./repos/region-north-east
+          token: ${{ steps.app-token-2.outputs.token }}
+          fetch-depth: 1
+
+      # region-north-west
+      - name: Checkout region-north-west repository
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          repository: food-hygiene-uk/region-north-west
+          path: ./repos/region-north-west
+          token: ${{ steps.app-token-2.outputs.token }}
+          fetch-depth: 1
+
+      # region-northern-ireland
+      - name: Checkout region-northern-ireland repository
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          repository: food-hygiene-uk/region-northern-ireland
+          path: ./repos/region-northern-ireland
+          token: ${{ steps.app-token-2.outputs.token }}
+          fetch-depth: 1
+
+      # region-scotland
+      - name: Checkout region-scotland repository
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          repository: food-hygiene-uk/region-scotland
+          path: ./repos/region-scotland
+          token: ${{ steps.app-token-2.outputs.token }}
+          fetch-depth: 1
+
+      # region-south-east
+      - name: Checkout region-south-east repository
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          repository: food-hygiene-uk/region-south-east
+          path: ./repos/region-south-east
+          token: ${{ steps.app-token-2.outputs.token }}
+          fetch-depth: 1
+
+      # region-south-west
+      - name: Checkout region-south-west repository
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          repository: food-hygiene-uk/region-south-west
+          path: ./repos/region-south-west
+          token: ${{ steps.app-token-2.outputs.token }}
+          fetch-depth: 1
+
+      # region-wales
+      - name: Checkout region-wales repository
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          repository: food-hygiene-uk/region-wales
+          path: ./repos/region-wales
+          token: ${{ steps.app-token-2.outputs.token }}
+          fetch-depth: 1
+
+      # region-west-midlands
+      - name: Checkout region-west-midlands repository
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          repository: food-hygiene-uk/region-west-midlands
+          path: ./repos/region-west-midlands
+          token: ${{ steps.app-token-2.outputs.token }}
+          fetch-depth: 1
+
+      # region-yorkshire-and-the-humber
+      - name: Checkout region-yorkshire-and-the-humber repository
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          repository: food-hygiene-uk/region-yorkshire-and-the-humber
+          path: ./repos/region-yorkshire-and-the-humber
+          token: ${{ steps.app-token-2.outputs.token }}
+          fetch-depth: 1
+
+      - name: Define ENV variable for regions
+        run: echo "REGIONS=('east-midlands' 'east-of-england' 'london' 'north-east' 'north-west' 'northern-ireland' 'scotland' 'south-east' 'south-west' 'wales' 'west-midlands' 'yorkshire-and-the-humber')" >> $GITHUB_ENV
+
+      - name: Loop over and commit each region's repository
+        env:
+          GITHUB_TOKEN: ${{ steps.app-token-2.outputs.token }}
+        run: |
+          for REGION in "${REGIONS[@]}"; do
+            echo "Processing region: ${REGION}"
+
+            # Prepare public directory
+            find ./repos/region-${REGION}/public -depth -delete
+            mv ./dist-temp/region-${REGION} ./repos/region-${REGION}/public
+
+            cd ./repos/region-${REGION}
+
+            git config --local user.name "${{ steps.app-token-2.outputs.app_slug }}[bot]"
+            git config --local user.email "${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token-2.outputs.app_slug }}[bot]@users.noreply.github.com"
+
+            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/food-hygiene-uk/region-${REGION}
+
+            if ! git diff --quiet || ! git ls-files --others --exclude-standard --quiet; then
+              git add .
+              git commit -m "Content update from main-site-builder deploy.yml"
+              git push origin HEAD:${{ github.ref_name }} || { echo "Failed to push changes"; exit 1; }
+            else
+              echo "No changes detected"
+            fi
+            cd ../../
+          done
+
+      # Create another GitHub App token to avoid token timeout issues
+      - name: Create GitHub App token
+        id: app-token-3
+        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
+        with:
+          app-id: ${{ secrets.APP_ID }}
+          private-key: ${{ secrets.APP_PRIVATE_KEY }}
+          owner: ${{ github.repository_owner }}
+
+      # food-hygiene-uk.github.io -- Root Site
       - name: Checkout GitHub Pages repository
         uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
         with:
           repository: food-hygiene-uk/food-hygiene-uk.github.io
-          path: ./repos/gh-pages
-          token: ${{ steps.app-token-2.outputs.token }}
+          path: ./repos/food-hygiene-uk.github.io
+          token: ${{ steps.app-token-3.outputs.token }}
           fetch-depth: 1
 
       - name: Prepare public directory
-        run: find ./repos/gh-pages/public -depth -delete
+        run: find ./repos/food-hygiene-uk.github.io/public -depth -delete
 
       - name: Move and rename generated site
-        run: mv ./dist-temp ./repos/gh-pages/public
+        run: mv ./dist-temp ./repos/food-hygiene-uk.github.io/public
 
       - name: Configure Git
-        working-directory: ./repos/gh-pages
+        working-directory: ./repos/food-hygiene-uk.github.io
         run: |
-          git config --local user.name "${{ steps.app-token-2.outputs.app_slug }}[bot]"
-          git config --local user.email "${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token-2.outputs.app_slug }}[bot]@users.noreply.github.com"
+          git config --local user.name "${{ steps.app-token-3.outputs.app_slug }}[bot]"
+          git config --local user.email "${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token-3.outputs.app_slug }}[bot]@users.noreply.github.com"
 
       - name: Commit and push changes
-        working-directory: ./repos/gh-pages
+        working-directory: ./repos/food-hygiene-uk.github.io
         env:
-          GITHUB_TOKEN: ${{ steps.app-token-2.outputs.token }}
+          GITHUB_TOKEN: ${{ steps.app-token-3.outputs.token }}
         run: |
           git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/food-hygiene-uk/food-hygiene-uk.github.io.git
 
           if ! git diff --quiet || ! git ls-files --others --exclude-standard --quiet; then
             git add .
-            git commit -m "Update site"
+            git commit -m "Content update from main-site-builder deploy.yml"
             git push origin HEAD:${{ github.ref_name }} || { echo "Failed to push changes"; exit 1; }
           else
             echo "No changes detected"
