[Chore] Update formatter steps in CI workflows and remove unused prettier task

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -88,13 +88,14 @@ jobs:
         working-directory: ./repos/source
         run: deno lint
 
-      - name: Run Pretter
+      - name: Run formatter
         working-directory: ./repos/source
-        run: deno task prettier:check
-
-      - name: Run Deno fmt
-        working-directory: ./repos/source
-        run: deno fmt --check
+        run: |
+          deno task prettier:write && deno fmt --check
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "Error: Unformatted files detected. Please commit changes after running the formatter."
+            exit 1
+          fi
 
       - name: Run Deno check
         working-directory: ./repos/source
diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -54,11 +54,14 @@ jobs:
       - name: Run Deno lint
         run: deno lint .
 
-      - name: Run Pretter
-        run: deno task prettier:check
-
-      - name: Run Deno fmt
-        run: deno fmt --check .
+      - name: Run formatter
+        working-directory: ./repos/source
+        run: |
+          deno task prettier:write && deno fmt --check
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "Error: Unformatted files detected. Please commit changes after running the formatter."
+            exit 1
+          fi
 
       - name: Run Deno check
         run: deno check src/generate-site.mts
